config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :photos
  resources :mypages
  resources :cycles
  resources :categories
  resources :developpers
  resources :events
  resources :projects
  resources :issues
  resources :journals
  resources :about

  resources :blogs do
    resources :comments
  end

  resources :members
        get 'user/:id', to: 'users#show', as: :user
        patch 'user/:id', to: 'users#update'

  resources :home
  get '/:username', to: 'users#show_by_username',as: :username
    root to: "home#index"
  
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  get '*path', controller: 'application', action: 'render_404'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :genres, through: :blog_genres
  has_many :blog_genres
  has_many :photos, through: :blog_photos
  has_many :blog_photos 
  has_many :journals, through: :blog_journals
  has_many :blog_journals
  has_many :comments

 # attr_accessible :users_attributes

  validates :user_id, presence: true
  validates :title, presence: true, if: :not_draft?
  validates :content, length: {minimum: 141}, if: :image_nothing?, if: :not_draft?
#  validate :user_image_exist


  def self.top_page_blogs
    find_by_sql(["(select id, title, user_id, published_at as created_at, 'blog' as content_flg from blogs where (user_id, published_at) in ( select user_id, max(published_at) from blogs where draft_flg = false and published_at < :time_now group by user_id ) ) union all (select id, name as title, user_id, created_at, 'photo' as content_flg from photos where (user_id, created_at) in ( select user_id, max(created_at) from photos group by user_id ))  order by created_at desc", {time_now: Time.now()}])
  end

  def image_nothing?
    image.present? == false
  end

  def not_draft?
    draft_flg == false
  end

  scope :published, -> { where draft_flg: false }
  scope :published_before, -> (time){ where("published_at < ?", time) }
  scope :users, ->(user_id) { where("user_id = ?", user_id) }

  private
    def user_image_exist
      if ! blog.user.image.present?
        errors.add(:user_image, "can't be in the past")
      end
    end
end

app/models/blog_genre.rb
class BlogGenre < ActiveRecord::Base
  belongs_to :blog
  belongs_to :genre
end

app/models/blog_photo.rb
class BlogPhoto < ActiveRecord::Base
  belongs_to :blog
  belongs_to :photo
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  belongs_to :category
end

app/models/equip.rb
class Equip < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :genres, through: :equip_genres
  has_many :equip_genres
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
  belongs_to :open_range

  validates :open_range_id, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :blogs, through: :blog_genres
  has_many :blog_genres
  has_many :users, through: :user_genres
  has_many :user_genres
  has_many :equips, through: :equip_genres
  has_many :equip_genres
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :status
  has_many :journals
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :category, through: :category_journal_rels
  has_many :category_journal_rels
  has_many :moves
  belongs_to :open_range
  belongs_to :project
  belongs_to :issue


  validates :project_id, presence: true
  validates :open_range_id, presence: true

  def monthty_time_amount 
    Journal.find_by_sql('SELECT SUBSTRING(date, 1, 7) as yearmonth, SUM(TIME_TO_SEC(time)) as sec FROM journals GROUP BY SUBSTRING(date, 1, 7)' )
  end
end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/models/open_range.rb
class OpenRange < ActiveRecord::Base
  has_many :journals
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :blogs, through: :blog_photos
  has_many :blog_photos

  validates :name, presence: true
  validates :image, presence: true
  validates :comment,    length: { maximum: 255 } 
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :journals
  has_many :issues
  has_many :events
  belongs_to :category
  belongs_to :status
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  has_many :genres, through: :user_genres
  has_many :user_genres
  has_many :blogs
  has_many :photos
  mount_uploader :image, ImageUploader

  include GraphicalHasMany
  graphical_has_many :follows

  has_many :follows
  has_many :follows_as_target, class_name: 'Follow', foreign_key: 'target_user_id'

#  validates :image, presence: true
  validates :name, presence: true, uniqueness: true
  #validates :account_id, presence: true, uniqueness: true, format: { with: /\A[a-z0-9]+\z/i }
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :content, VideoUploader
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_filter :basic, only: [:edit, :update, :destroy]
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all.order('status_id')
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:subject, :project_id, :estimated_hours, :assigned_to_id, :status_id, :image_link)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_link %><br>
    <%= f.text_area :image_link %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :estimated_hours %><br>
    <%= f.number_field :estimated_hours %>
  </div>
  <div class="field">
    <%= f.label :assigned_to_id %><br>
    <%= f.number_field :assigned_to_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.number_field :status_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                          issues
                        </a>
                      </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body">
                        <div class="table-responsive">
                           <table class="table table-condensed">
  <thead>
    <tr>
      <th>Image</th>
      <th>Subject</th>
      <th>Project</th>
      <th>Estimated hours</th>
      <th>Journals</th>
      <th>journals time</th>
      <th>Assigned to</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <% total_time = 0 %>
      <tr>
        <td><% if issue.image_link.present? %><%= link_to lazy_image_tag(issue.image_link, style: 'width:100px;'), issue %><% end %></td>
        <td><%= issue.subject %></td>
        <td><%= link_to issue.project.title, issue.project %></td>
        <td><%= issue.estimated_hours %></td>
        <td>
          <% for journal in issue.journals.order('date desc') %>
          <% total_time += journal.time.min + journal.time.hour * 60 %>
          <% end %>
          <% issue.journals.order('date desc').each_with_index do |journal, i| %>
          <%= link_to journal.title, journal, class:"label" %>
          <%= '...' if i == 10 %>
          <% break if i == 10 %>
          <% end %>
        </td>
        <td><%= (total_time.to_f / 60).round(1) %></td>
        <td><%= issue.assigned_to_id %></td>
        <td><%= issue.status.title %></td>
        <td><%= link_to 'Show', issue %></td>
        <% if user_signed_in? %><td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>
</table>

                        </div>
                      </div>
                    </div>
                  </div>
              </div>
<% if user_signed_in? %>
<%= link_to 'New Issue', new_issue_path %>
<% end %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>image:</strong>
  <%= image_tag @issue.image_link %>
</p>
<p>
  <strong>Subject:</strong>
  <%= @issue.subject %>
</p>

<p>
  <strong>Project:</strong>
  <%= @issue.project.title %>
</p>

<p>
  <strong>Estimated hours:</strong>
  <%= @issue.estimated_hours %>
</p>
<p>
  <strong>Total Time:</strong>
<% total_time = 0 %>
          <% for journal in @issue.journals.order('date desc') %>
          <% total_time += journal.time.min + journal.time.hour * 60 %>
          <% end %>
<%= (total_time.to_f / 60).round(1) %>
</p>
<p>
<strong>Jouranls:</strong>
          <% for journal in @issue.journals %>
          <%= link_to journal.title, journal %>
          <% end %>
</p>


<p>
  <strong>Assigned to:</strong>
  <%= @issue.assigned_to_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.status.title %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_issue_path(@issue) %> |
<% end %>
<%= link_to 'Back', issues_path %>