config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :photos
  resources :mypages
  resources :cycles
  resources :categories
  resources :developpers
  resources :events
  resources :projects
  resources :issues
  resources :journals
  resources :about

  resources :blogs do
    resources :comments
  end

  resources :members
        get 'user/:id', to: 'users#show', as: :user
        patch 'user/:id', to: 'users#update'

  resources :home
  get '/:username', to: 'users#show_by_username',as: :username
    root to: "home#index"
  
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  get '*path', controller: 'application', action: 'render_404'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :genres, through: :blog_genres
  has_many :blog_genres
  has_many :photos, through: :blog_photos
  has_many :blog_photos 
  has_many :journals, through: :blog_journals
  has_many :blog_journals
  has_many :comments

 # attr_accessible :users_attributes

  validates :user_id, presence: true
  validates :title, presence: true, if: :not_draft?
  validates :content, length: {minimum: 141}, if: :image_nothing?, if: :not_draft?
#  validate :user_image_exist


  def self.top_page_blogs
    find_by_sql(["(select id, title, user_id, published_at as created_at, 'blog' as content_flg from blogs where (user_id, published_at) in ( select user_id, max(published_at) from blogs where draft_flg = false and published_at < :time_now group by user_id ) ) union all (select id, name as title, user_id, created_at, 'photo' as content_flg from photos where (user_id, created_at) in ( select user_id, max(created_at) from photos group by user_id ))  order by created_at desc", {time_now: Time.now()}])
  end

  def image_nothing?
    image.present? == false
  end

  def not_draft?
    draft_flg == false
  end

  scope :published, -> { where draft_flg: false }
  scope :published_before, -> (time){ where("published_at < ?", time) }
  scope :users, ->(user_id) { where("user_id = ?", user_id) }

  private
    def user_image_exist
      if ! blog.user.image.present?
        errors.add(:user_image, "can't be in the past")
      end
    end
end

app/models/blog_genre.rb
class BlogGenre < ActiveRecord::Base
  belongs_to :blog
  belongs_to :genre
end

app/models/blog_photo.rb
class BlogPhoto < ActiveRecord::Base
  belongs_to :blog
  belongs_to :photo
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  belongs_to :category
end

app/models/equip.rb
class Equip < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :genres, through: :equip_genres
  has_many :equip_genres
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
  belongs_to :open_range

  validates :open_range_id, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :blogs, through: :blog_genres
  has_many :blog_genres
  has_many :users, through: :user_genres
  has_many :user_genres
  has_many :equips, through: :equip_genres
  has_many :equip_genres
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :status
  has_many :journals
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :category, through: :category_journal_rels
  has_many :category_journal_rels
  has_many :moves
  belongs_to :open_range
  belongs_to :project
  belongs_to :issue


  validates :project_id, presence: true
  validates :open_range_id, presence: true

  def monthty_time_amount 
    Journal.find_by_sql('SELECT SUBSTRING(date, 1, 7) as yearmonth, SUM(TIME_TO_SEC(time)) as sec FROM journals GROUP BY SUBSTRING(date, 1, 7)' )
  end
end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/models/open_range.rb
class OpenRange < ActiveRecord::Base
  has_many :journals
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :blogs, through: :blog_photos
  has_many :blog_photos

  validates :name, presence: true
  validates :image, presence: true
  validates :comment,    length: { maximum: 255 } 
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :journals
  has_many :issues
  has_many :events
  belongs_to :category
  belongs_to :status
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  has_many :genres, through: :user_genres
  has_many :user_genres
  has_many :blogs
  has_many :photos
  mount_uploader :image, ImageUploader

  include GraphicalHasMany
  graphical_has_many :follows

  has_many :follows
  has_many :follows_as_target, class_name: 'Follow', foreign_key: 'target_user_id'

#  validates :image, presence: true
  validates :name, presence: true, uniqueness: true
  #validates :account_id, presence: true, uniqueness: true, format: { with: /\A[a-z0-9]+\z/i }
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :content, VideoUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
skip_before_filter :verify_authenticity_token
  respond_to :html

  def index
    @projects = Project.order('status_id asc')
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :content, :category_id, :start_datetime, :end_datetime, :status_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :start_datetime %><br>
    <%= f.datetime_select :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime %><br>
    <%= f.datetime_select :end_datetime %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status_id, Status.all.map{|t| [t.title, t.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
          <div class="row">
            <div class="col-lg-12">
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                          projects
                        </a>
                      </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body">
                        <div class="table-responsive">
			   <table class="table table-condensed">
                            <thead>
                              <tr>
                                <th>image</th>
                                <th>Title</th>
                                <th>issues</th>
                                <th>journals</th>
                                <th>events</th>
                                <th>Category</th>
                                <th>Start datetime</th>
                                <th>End datetime</th>
                                <th>status</th>
                                <th></th>
                              </tr>
                            </thead>
                            <tbody>
                              <% @projects.each do |project| %>
                                <tr style="height:60px;overflow:hidden;">
                                  <td><% if project.content.present? %><%= lazy_image_tag project.content, style: 'width:60px;' %><% end %></td>
                                  <td><%= project.title %></td>
                                  <td><%= link_to project.issues.count, project %></td>
                                  <td><%= link_to project.journals.count, project %></td>
                                  <td><%= link_to project.events.count, project %></td>
                                  <td><%= project.category.title %></td>
                                  <td><%= project.start_datetime.strftime("%Y-%m-%d") %></td>
                                  <td><%= project.end_datetime.strftime("%Y-%m-%d") %></td>
                                  <td><%= project.status.title %></td>
                                  <td><% if user_signed_in? %><%= link_to 'Show', project %>
                                  <%= link_to 'Edit', edit_project_path(project) %>
                                  <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
                                </tr>
                              <% end %>
                            </tbody>
                          </table>

                          <br>
                          <% if user_signed_in? %>
                          <%= link_to 'New Project', new_project_path %>
                          <% end %>

                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<strong><%= link_to 'project top', projects_path %></strong>
<p>
  <h2><%= @project.title %></h2>
</p>

<p>
  <strong>image:</strong>
  <%= image_tag @project.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to @project.category.title, @project.category %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status.title %>
</p>

<p>
  <strong>Start datetime:</strong>
  <%= @project.start_datetime.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>End datetime:</strong>
  <%= @project.end_datetime.strftime("%Y-%m-%d %H:%M") %>
</p>

                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                          issues
                        </a>
                      </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body">
                        <div class="table-responsive">
                          <table class="table" >
                            <thead>
                              <tr>
                                <th>Image</th>
                                <th>Subject</th>
                                <th>extimated_hours</th>
                                <th>journals</th>
                                <th>jouranls sum time</th>
                                <th>assigned to</th>
                                <th>status</th>
                                <th></th>
                                <th></th>
                                <th></th>
                              </tr>
                            </thead>
                            <tbody>
                              <% for issue in @project.issues %>
      <% total_time = 0 %>
      <tr>
        <td><%= image_tag issue.image_link %></td>
        <td><%= issue.subject %></td>
        <td><%= issue.estimated_hours %></td>
        <td>          <% for journal in issue.journals %>
          <% total_time += journal.time.min + journal.time.hour * 60 %>
          <% end %>
          <% issue.journals.each_with_index do |journal, i| %>
          <%= link_to journal.title, journal, class:"label" %>
          <%= '...' if i == 10 %>
          <% break if i == 10 %>
          <% end %>
        </td>        <td><%= (total_time.to_f / 60).round(1) %></td>
        <td><%= issue.assigned_to_id %></td>
        <td><%= issue.status.title %></td>
        <td><%= link_to 'Show', issue %></td>
        <% if user_signed_in? %><td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
                              <% end %>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingTwo">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                          events
                        </a>
                      </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body">
                        <div class="table-responsive">
                          <table class="table" >
                            <thead>
                              <tr>
                                <th>Title</th>
                                <th>startTime</th>
                                <th>place</th>
                                <th>Content</th>
                                <th>project</th>
                                <th>category</th>
                                <th>Distance</th>
                                <th>Content</th>
                                <th></th>
                              </tr>
                            </thead>
                            <tbody>
                              <% for event in @project.events.order('start desc') %>
                                <tr>
                                  <td><%= event.title %></td>
                                  <td><%= event.start.strftime("%Y/%m/%d") %></td>
                                  <td><%= event.place %></td>
                                  <td><%= event.content %></td>
                                  <td><%= event.project.title %></td>
                                  <td><%= event.category.title %></td>
                                  <td><%= link_to 'Show', journal %>
                                  <% if user_signed_in? %><%= link_to 'Edit', edit_event_path(event) %>
                                  <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %><% end %>
                                </tr>
                              <% end %>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingThree">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                          journals
                        </a>
                      </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body">
                        <div class="table-responsive">
                          <table class="table" >
                            <thead>
                              <tr>
                                <th>Title</th>
                                <th>Time</th>
                                <th>Cost</th>
                                <th>Cost per hour</th>
                                <th>Date</th>
                                <th>Place</th>
                                <th>Distance</th>
                                <th>Content</th>
                                <th>Open range</th>
                                <th></th>
                              </tr>
                            </thead>
                            <tbody>
                              <% for journal in @project.journals.order('date desc') %>
                                <tr>
                                  <td><%= journal.title %></td>
                                  <td><%= journal.time.strftime("%H:%M:%S") %></td>
                                  <td><%= journal.cost %></td>
                                  <td><%= journal.cost.present? ? (journal.cost / (journal.time.hour.to_f + (journal.time.min.to_f / 60))).round(1) : nil %></td>
                                  <td><%= journal.date %></td>
                                  <td><%= journal.place %></td>
                                  <td><%= journal.distance %></td>
                                  <td><%= journal.content %></td>
                                  <td><%= journal.open_range.title %></td>
                                  <td><%= link_to 'Show', journal %>
                                  <% if user_signed_in? %><%= link_to 'Edit', edit_journal_path(journal) %>
                                  <%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %><% end %>
                                </tr>
                              <% end %>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                </div>
            </div>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'project top', projects_path %>