config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :photos
  resources :mypages
  resources :cycles
  resources :categories
  resources :developpers
  resources :events
  resources :projects
  resources :issues
  resources :journals
  resources :about

  resources :blogs do
    resources :comments
  end

  resources :members
        get 'user/:id', to: 'users#show', as: :user
        patch 'user/:id', to: 'users#update'

  resources :home
  get '/:username', to: 'users#show_by_username',as: :username
    root to: "home#index"
  
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  get '*path', controller: 'application', action: 'render_404'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :genres, through: :blog_genres
  has_many :blog_genres
  has_many :photos, through: :blog_photos
  has_many :blog_photos 
  has_many :journals, through: :blog_journals
  has_many :blog_journals
  has_many :comments

 # attr_accessible :users_attributes

  validates :user_id, presence: true
  validates :title, presence: true, if: :not_draft?
  validates :content, length: {minimum: 141}, if: :image_nothing?, if: :not_draft?
#  validate :user_image_exist


  def self.top_page_blogs
    find_by_sql(["(select id, title, user_id, published_at as created_at, 'blog' as content_flg from blogs where (user_id, published_at) in ( select user_id, max(published_at) from blogs where draft_flg = false and published_at < :time_now group by user_id ) ) union all (select id, name as title, user_id, created_at, 'photo' as content_flg from photos where (user_id, created_at) in ( select user_id, max(created_at) from photos group by user_id ))  order by created_at desc", {time_now: Time.now()}])
  end

  def image_nothing?
    image.present? == false
  end

  def not_draft?
    draft_flg == false
  end

  scope :published, -> { where draft_flg: false }
  scope :published_before, -> (time){ where("published_at < ?", time) }
  scope :users, ->(user_id) { where("user_id = ?", user_id) }

  private
    def user_image_exist
      if ! blog.user.image.present?
        errors.add(:user_image, "can't be in the past")
      end
    end
end

app/models/blog_genre.rb
class BlogGenre < ActiveRecord::Base
  belongs_to :blog
  belongs_to :genre
end

app/models/blog_photo.rb
class BlogPhoto < ActiveRecord::Base
  belongs_to :blog
  belongs_to :photo
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  belongs_to :category
end

app/models/equip.rb
class Equip < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :genres, through: :equip_genres
  has_many :equip_genres
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
  belongs_to :open_range

  validates :open_range_id, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :blogs, through: :blog_genres
  has_many :blog_genres
  has_many :users, through: :user_genres
  has_many :user_genres
  has_many :equips, through: :equip_genres
  has_many :equip_genres
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :status
  has_many :journals
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :category, through: :category_journal_rels
  has_many :category_journal_rels
  has_many :moves
  belongs_to :open_range
  belongs_to :project
  belongs_to :issue


  validates :project_id, presence: true
  validates :open_range_id, presence: true

  def monthty_time_amount 
    Journal.find_by_sql('SELECT SUBSTRING(date, 1, 7) as yearmonth, SUM(TIME_TO_SEC(time)) as sec FROM journals GROUP BY SUBSTRING(date, 1, 7)' )
  end
end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/models/open_range.rb
class OpenRange < ActiveRecord::Base
  has_many :journals
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :blogs, through: :blog_photos
  has_many :blog_photos

  validates :name, presence: true
  validates :image, presence: true
  validates :comment,    length: { maximum: 255 } 
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :journals
  has_many :issues
  has_many :events
  belongs_to :category
  belongs_to :status
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  has_many :genres, through: :user_genres
  has_many :user_genres
  has_many :blogs
  has_many :photos
  mount_uploader :image, ImageUploader

  include GraphicalHasMany
  graphical_has_many :follows

  has_many :follows
  has_many :follows_as_target, class_name: 'Follow', foreign_key: 'target_user_id'

#  validates :image, presence: true
  validates :name, presence: true, uniqueness: true
  #validates :account_id, presence: true, uniqueness: true, format: { with: /\A[a-z0-9]+\z/i }
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :content, VideoUploader
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  before_filter :basic
  respond_to :html

  def index
    @memos = Memo.all
    respond_with(@memos)
  end

  def show
    respond_with(@memo)
  end

  def new
    @memo = Memo.new
    respond_with(@memo)
  end

  def edit
  end

  def create
    @memo = Memo.new(memo_params)
    @memo.save
    respond_with(@memo)
  end

  def update
    @memo.update(memo_params)
    respond_with(@memo)
  end

  def destroy
    @memo.destroy
    respond_with(@memo)
  end

  private
    def set_memo
      @memo = Memo.find(params[:id])
    end

    def memo_params
      params.require(:memo).permit(:content)
    end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= form_for(@memo) do |f| %>
  <% if @memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, :class => "form-control", :rows => 20 %>
  </div>
  <div class="actions">
    <%= f.submit class:"form-control" %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<p>Editing Memo</p>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
         <div class="row">
            <div class="col-lg-12">
              <p id="notice"><%= notice %></p>
<% if current_user.id == 1 %>
              <h1>Memos</h1>
                <table class="table">
                  <thead>
                    <tr>
                      <th>Content</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @memos.each do |memo| %>
                    <tr>
                      <td><%=simple_format(memo.content, {}, {:sanitize => false} ) %></td>
                      <td><%= link_to 'Show', memo %></td>
                      <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
                      <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              <br>
<% end %>
            </div>
          </div>
<p><%= link_to 'プロフィール変更' , edit_member_path(current_user) %></p>
<p><%= link_to 'パスワード・アドレス変更', edit_user_registration_path %></p>
<p><%= link_to "log out", destroy_user_session_path , method: :delete %></p>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Content:</strong>
  <%= simple_format(@memo.content, {}, {:sanitize => false} ) %>
</p>
<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>